server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017
      database: mydatabase
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer